import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {sealLocalDefault} from '../src/local-default.js';
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.PLAYWRIGHT_PATH));}
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1500,height:1050}}),page=await context.newPage();
const out=new URL('../test-results/',import.meta.url);await mkdir(out,{recursive:true});const checks=[],errors=[];
await context.route('**/private/default-access.json',r=>r.fulfill({json:awaitDefault}));const awaitDefault=await sealLocalDefault('sk-synthetic-batch-suite-not-a-live-key');
await context.route('https://api.agnes-ai.cn/**',()=>{throw Error('Batch import must not call paid APIs');});page.on('pageerror',e=>errors.push(e.message));
const assets=()=>page.evaluate(async()=>{const {get}=await import('./src/storage.js');return (await get('state','project')).assets;});
const done=()=>page.waitForFunction(()=>document.querySelector('#asset-operation-dialog').getAttribute('aria-busy')==='false'&&!document.querySelector('#asset-operation-progress').hidden);
try{
  await page.goto((process.env.XAI_TEST_URL||'http://127.0.0.1:4173/'));await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');await page.locator('#experience-expert').click();await page.locator('#mode-single').click();
  await page.locator('#prompt').fill('单段草稿：保留这里的画面描述。');await page.locator('#dialogue').fill('单段台词');await page.locator('#shot-id').fill('');await page.locator('#episode').fill('');await page.locator('#seconds').selectOption('12');await page.locator('#aspect').selectOption('1:1');await page.locator('#generation-mode').selectOption('keyframe');await page.locator('#seed').fill('123');
  const singleColor=await page.locator('#job-form').evaluate(el=>({form:getComputedStyle(el).backgroundColor,button:getComputedStyle(document.querySelector('#add-jobs')).backgroundColor}));
  await page.locator('#mode-batch').click();assert.equal(await page.locator('#mode-batch').getAttribute('aria-selected'),'true');assert.match(await page.locator('#creation-mode-note').textContent(),/下方清单/);
  assert.equal(await page.locator('#single-editor').isVisible(),false);assert.equal(await page.locator('#prompt').isDisabled(),true);assert.equal(await page.locator('#drop-zone').isVisible(),false);assert.equal(await page.locator('#batch-panel').isVisible(),true);assert.equal(await page.locator('#batch-input').isEnabled(),true);
  assert.match(await page.locator('#batch-defaults-summary').textContent(),/12 秒 · 16:9 · EP01/);
  const batchColor=await page.locator('#job-form').evaluate(el=>({form:getComputedStyle(el).backgroundColor,button:getComputedStyle(document.querySelector('#add-jobs')).backgroundColor}));assert.notEqual(singleColor.form,batchColor.form);assert.notEqual(singleColor.button,batchColor.button);
  assert.match(await page.locator('.version').textContent(),/X-AI 1\.2\.1.*® YiQiXP/);assert.equal(await page.locator('.version').isVisible(),true);assert.equal(await page.locator('[data-release-date]').count(),0);assert.equal(await page.locator('.sidebar-copyright').count(),0);
  const footerLine=await page.locator('.version').evaluate(el=>{const a=el.querySelector('span').getBoundingClientRect(),b=el.querySelector('strong').getBoundingClientRect();return Math.abs(a.top-b.top)<3&&a.right<b.left;});assert.equal(footerLine,true);
  const tabStyle=await page.locator('.segmented').evaluate(el=>{const a=getComputedStyle(el.querySelector('#mode-single')),b=getComputedStyle(el.querySelector('#mode-batch'));return {different:a.backgroundColor!==b.backgroundColor,white:b.color==='rgb(255, 255, 255)'};});assert.deepEqual(tabStyle,{different:true,white:true});
  await page.screenshot({path:fileURLToPath(new URL('mode-batch.png',out))});await page.locator('#mode-batch').press('ArrowLeft');assert.equal(await page.locator('#mode-single').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#batch-panel').isVisible(),false);await page.screenshot({path:fileURLToPath(new URL('mode-single.png',out))});
  assert.equal(await page.locator('#prompt').isEnabled(),true);assert.equal(await page.locator('#batch-input').isDisabled(),true);assert.equal(await page.locator('#prompt').inputValue(),'单段草稿：保留这里的画面描述。');
  checks.push('independent single/batch controls, fieldsets and drafts; distinct form/button colors; keyboard switching; compact one-line copyright');
  await page.evaluate(async()=>{
    const root=await navigator.storage.getDirectory(),source=await root.getDirectoryHandle('故事项目',{create:true}),output=await root.getDirectoryHandle('X-AI-test',{create:true});
    const proto=Object.getPrototypeOf(root);proto.queryPermission=async()=> 'granted';proto.requestPermission=async()=> 'granted';
    const {writeFile}=await import('./src/storage.js');
    const image=async(w,h,c)=>{const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const x=canvas.getContext('2d');x.fillStyle=c;x.fillRect(0,0,w,h);return new Promise(r=>canvas.toBlob(r,'image/png'));};
    await writeFile(source,'images/C01_熊.png',await image(720,1280,'#8c72b2'));
    await writeFile(source,'images/S01_长图.png',await image(1800,600,'#507f82'));
    await writeFile(source,'images/C01_历史.png',await image(512,512,'#666666'));
    await writeFile(source,'images/未引用.png',await image(512,512,'#abc123'));
    await writeFile(source,'lists/shots.csv','镜号;时长秒;画面动作;参考图;角色五视图引用\nA01-01;8;小熊抬头;"C01=../images/C01_熊.png|S01=../images/S01_长图.png";历史.png\nA01-02;8;小熊走路;C01;不用.png');
    await writeFile(output,'references/原有素材.txt','existing reference content');await writeFile(output,'references/nested/旧图.txt','nested old content');
    window.__source=source;window.__output=output;window.showDirectoryPicker=async({id})=>id==='x-ai-input'?source:output;
    window.__files=async function list(dir,p=''){const all=[];for await(const [name,e]of dir.entries())if(e.kind==='directory')all.push(...await list(e,p+name+'/'));else all.push(p+name);return all;};
  });
  await page.locator('#choose-folder').click();await page.waitForFunction(()=>document.querySelector('#directory-desc').textContent.includes('已授权'));
  assert.match(await page.locator('#directory-location-label').textContent(),/X-AI-test/);assert.match(await page.locator('#directory-backup-status').textContent(),/已备份 2 个/);
  const backup=await page.evaluate(async()=>{const {readFile,sha256}=await import('./src/storage.js').then(async m=>({...m,...await import('./src/core.js')}));const files=await __files(__output);const manifestPath=files.find(p=>p.startsWith('backups/')&&p.endsWith('/manifest.json')),m=JSON.parse(await(await readFile(__output,manifestPath)).text());return {count:m.files.length,valid:(await Promise.all(m.files.map(async f=>await sha256(await readFile(__output,f.backup))===f.sha256))).every(Boolean)};});assert.deepEqual(backup,{count:2,valid:true});
  checks.push('selected output directory is visible; existing references and nested files are backed up with verified hashes before writing');
  await page.locator('#mode-batch').click();await page.locator('#batch-source-folder').click();await page.waitForFunction(()=>document.querySelector('#batch-input').value.includes('A01-02'));
  await page.locator('#batch-defaults>summary').click();await page.locator('#batch-seconds').selectOption('6');await page.locator('#batch-aspect').selectOption('16:9');await page.locator('#batch-episode').fill('B00');await page.locator('#batch-id-prefix').fill('B');await page.locator('#batch-defaults>summary').click();
  assert.match(await page.locator('#batch-source-location').textContent(),/故事项目.*lists\/shots.csv/);assert.match(await page.locator('#batch-analysis').textContent(),/表格 · 分号.*2 镜/);
  await page.locator('#batch-read-assets').click();await page.locator('#asset-operation-dialog').waitFor();assert.equal((await assets()).length,0);
  assert.match(await page.locator('#asset-storage-note').textContent(),/不复制到 references/);await page.locator('#asset-operation-start').click();await done();
  const original=await assets();assert.equal(original.length,2);assert.ok(original.every(a=>a.storage==='source'&&a.path.startsWith('images/')));assert.deepEqual(new Set(original.flatMap(a=>a.aliases)),new Set(['C01','S01']));
  let files=await page.evaluate(()=>__files(__output));assert.equal(files.filter(p=>p.startsWith('references/')).length,2);assert.ok(!files.some(p=>p.includes('熊.png')||p.includes('长图.png')));
  checks.push('one folder grant resolves CSV sibling/parent paths and codes; only two referenced assets read, no originals copied into output references');
  await page.locator('#asset-operation-done').click();await page.locator('#batch-open-library').click();await page.locator('#assets-select-issues').click();await page.locator('#assets-batch-optimize').click();await page.locator('#asset-operation-start').click();await done();
  const current=await assets(),raw=current.find(a=>a.name==='S01_长图.png'&&!a.derivedFrom),optimized=current.find(a=>a.derivedFrom===raw.id);
  assert.equal(optimized.name,raw.name);assert.ok(optimized.path.startsWith('references/optimized/'));assert.equal(optimized.path.split('/').at(-1),'S01_长图.png');assert.equal(raw.effectiveAssetId,optimized.id);assert.deepEqual(optimized.errors,[]);
  const integrity=await page.evaluate(async({raw,opt})=>{const {readFile}=await import('./src/storage.js'),{sha256}=await import('./src/core.js');const original=await readFile(__source,raw.path),copy=await readFile(__output,opt.path);return {original:await sha256(original),copy:await sha256(copy),signature:[...new Uint8Array(await copy.slice(0,4).arrayBuffer())]};},{raw,opt:optimized});
  assert.equal(integrity.original,raw.sha256);assert.equal(integrity.copy,optimized.sha256);assert.deepEqual(integrity.signature,[137,80,78,71]);
  checks.push('optimization preserves original bytes and full PNG filename, writes only optimized media to references, and records the effective replacement');
  await page.locator('#asset-operation-done').click();await page.locator('#assets-version-filter').selectOption('original');await page.locator(`[data-select-asset="${raw.id}"]`).click();assert.equal(await page.locator(`[data-asset-thumb="${optimized.id}"]`).count(),1);await page.locator('#library-return-studio').click();await page.locator('#batch-check').click();await page.screenshot({path:fileURLToPath(new URL('batch-source-preview.png',out)),fullPage:true});
  await page.locator('#add-jobs').click();await page.locator('#queue-view').waitFor();const jobs=await page.evaluate(async()=>{const {get}=await import('./src/storage.js');return(await get('state','project')).jobs;});assert.equal(jobs.length,2);assert.ok(jobs[0].assetIds.includes(optimized.id));assert.ok(!jobs[0].assetIds.includes(raw.id));assert.ok(jobs[0].sourceReferences.includes('S01=../images/S01_长图.png'));assert.equal(jobs[1].assetIds.length,1);
  assert.ok(jobs.every(j=>j.episode==='B00'&&j.aspect==='16:9'&&j.seconds===8&&j.mode==='reference'&&j.dialogue===''&&j.seed===null&&!j.firstFrame&&!j.lastFrame));assert.equal(await page.locator('#shot-id').inputValue(),'');assert.equal(await page.locator('#selected-assets [data-asset-thumb]').count(),0);assert.equal(await page.locator('#batch-selected-assets [data-asset-thumb]').count(),1);
  checks.push('batch defaults and material selection are independent; CSV values win; disabled empty single fields do not block batch submission or lose the single draft');
  const payloadCheck=await page.evaluate(async()=>{const {get,readFile}=await import('./src/storage.js'),{Runner}=await import('./src/engine.js'),{sha256}=await import('./src/core.js');const project=await get('state','project'),r=new Runner(()=>({project,folder:__output}),()=>{},()=>{}),payload=await r.payload(project.jobs[0]),data=new Blob([Uint8Array.from(atob(payload.images[1].split(',')[1]),c=>c.charCodeAt(0))]);const map=JSON.parse(await(await readFile(__output,'reference-mapping.json')).text());return {hash:await sha256(data),maps:map.mappings.length};});assert.equal(payloadCheck.hash,optimized.sha256);assert.equal(payloadCheck.maps,2);
  checks.push('queued jobs and actual encoded request use the optimized asset, preserve original CSV tokens, and export the path mapping');
  // Backup failure leaves existing references unchanged and aborts further writes.
  const blocked=await page.evaluate(async()=>{const {backupReferences,readFile}=await import('./src/storage.js');const old=await(await readFile(__output,'references/原有素材.txt')).text();const broken={getDirectoryHandle:async(name,opts)=>{if(name==='backups')throw Error('simulated disk failure');return __output.getDirectoryHandle(name,opts);},queryPermission:async()=> 'granted'};let error='';try{await backupReferences(broken);}catch(e){error=e.message;}return {error,unchanged:old===await(await readFile(__output,'references/原有素材.txt')).text()};});assert.match(blocked.error,/simulated disk failure/);assert.equal(blocked.unchanged,true);
  checks.push('backup write failure is propagated and leaves original reference files intact');
  await page.locator('[data-view=studio]').click();await page.locator('#batch-input').fill('镜号,提示词,参考图\nB01,走路,../../../outside.png');await page.locator('#batch-read-assets').click();assert.match(await page.locator('#batch-analysis').textContent(),/超出授权目录/);assert.equal(await page.locator('#asset-operation-dialog').isVisible(),false);assert.equal((await assets()).length,3);
  await page.locator('#batch-input').fill('镜号,提示词,参考图\nB01,走路,../images/missing.png');await page.locator('#batch-read-assets').click();assert.match(await page.locator('#batch-analysis').textContent(),/文件不存在/);
  checks.push('out-of-root and missing paths report exact references without guessing or importing partial batches');
  const changed=await page.evaluate(async()=>{const {readAsset,writeFile,get}=await import('./src/storage.js');const a=(await get('state','project')).assets.find(a=>a.name==='C01_熊.png');await writeFile(__source,a.path,'changed original');try{await readAsset(a);return false;}catch(e){return e.message.includes('原文件已改变');}});assert.equal(changed,true);
  checks.push('submission reads original source and rejects a changed file instead of silently using stale cached bytes');
  const audio=await page.evaluate(async()=>{
    const {importAsset,trimAudio}=await import('./src/media.js'),{blob}=await import('./src/storage.js'),{sha256}=await import('./src/core.js');
    const bytes=await(await fetch('./tests/fixtures/synthetic.mp4')).blob(),original=await importAsset(new File([bytes],'对白.m4a',{type:'audio/mp4'}),{storage:'source',sources:[{root:'audio-test',rootName:'音频目录',path:'声音/对白.m4a'}]});
    const trimmed=await trimAudio(original,0,2);return {name:trimmed.name,path:trimmed.path,duration:trimmed.duration,unchanged:await sha256(await blob(original.blobKey))===original.sha256};
  });assert.equal(audio.name,'对白.m4a');assert.ok(audio.path.startsWith('references/optimized/'));assert.equal(audio.path.split('/').at(-1),'对白.m4a');assert.ok(Math.abs(audio.duration-2)<.1);assert.equal(audio.unchanged,true);
  checks.push('source audio trimming preserves the M4A filename and encoding, stores the result in references, and leaves original bytes intact');
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('.version').isVisible(),false);assert.equal(await page.locator('.mobile-copyright').count(),0);assert.deepEqual(errors,[]);
  await writeFile(new URL('batch-results.json',out),JSON.stringify({at:new Date().toISOString(),checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks},null,2));
}finally{await context.close();await browser.close();}
