// Exercise the real user entry points with synthetic credentials and controlled responses only.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {sealLocalDefault} from '../src/local-default.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],checks=[];
const synthetic=await sealLocalDefault('sk-synthetic-experience-no-real-key'),media=await readFile('tests/fixtures/synthetic.mp4');
await context.route('**/private/default-access.json',r=>r.fulfill({json:synthetic}));
await context.route('https://**',r=>{errors.push('Unexpected external call '+r.request().url());return r.abort();});
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{errors.push('Unexpected dialog '+d.message());d.dismiss();});
try{
  await context.addInitScript(()=>{const OriginalDate=Date;window.__clockOffset=0;window.Date=class extends OriginalDate{constructor(...args){super(...(args.length?args:[OriginalDate.now()+window.__clockOffset]));}static now(){return OriginalDate.now()+window.__clockOffset;}};});
  const expireCooldown=async()=>{await page.evaluate(()=>window.__clockOffset+=61000);await page.waitForFunction(()=>!document.querySelector('#pavo-submit').disabled);};
  const base=process.env.XAI_TEST_URL||'http://127.0.0.1:4183/';await page.goto(base);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  assert.match(await page.locator('#pavo-settings-summary').textContent(),/16:9.*12s.*720p/);
  await page.locator('#pavo-settings-toggle').click();assert.equal(await page.locator('#pavo-settings').isVisible(),true);await page.locator('#pavo-prompt').click({position:{x:8,y:8}});assert.equal(await page.locator('#pavo-settings').isVisible(),false);await page.locator('#pavo-settings-toggle').click();await page.locator('#pavo-library').focus();assert.equal(await page.locator('#pavo-settings').isVisible(),false);await page.locator('#pavo-settings-toggle').click();await page.locator('#pavo-settings-toggle').press('Escape');assert.equal(await page.locator('#pavo-settings').isVisible(),false);
  checks.push('Pavo starts with 16:9 / 12s / 720p; pointer outside, keyboard focus outside and Escape dismiss settings');
  assert.equal(await page.locator('#experience-easy').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#shot-id').isVisible(),false);assert.equal(await page.locator('#pavo-prompt').isVisible(),true);assert.equal(await page.locator('#mode-pavo').getAttribute('aria-selected'),'true');assert.equal(await page.locator('.studio-aside').isVisible(),false);
  await page.locator('#experience-expert').click();await page.locator('#mode-single').click();assert.equal(await page.locator('#shot-id').isVisible(),true);assert.equal(await page.locator('.studio-aside').isVisible(),true);await page.locator('#experience-easy').click();
  for(const selector of ['.studio-project-bar','.directory-bar','#directory-details'])assert.equal(await page.locator(selector).isVisible(),false);
  const header=await page.locator('.topbar').evaluate(el=>{const bar=el.querySelector('.experience-bar'),r=el.getBoundingClientRect(),b=bar.getBoundingClientRect();return {inside:!!bar,centered:Math.abs((b.left+b.right)/2-(r.left+r.right)/2)<2};});assert.deepEqual(header,{inside:true,centered:true});
  await page.locator('#pavo-prompt').fill('保留 Pavo 草稿');await page.locator('#experience-expert').click();assert.equal(await page.locator('.studio-project-bar').isVisible(),true);assert.equal(await page.locator('.directory-bar').isVisible(),true);await page.locator('#mode-single').click();await page.locator('#prompt').fill('保留专家草稿');await page.locator('#experience-easy').click();assert.equal(await page.locator('#pavo-prompt').inputValue(),'保留 Pavo 草稿');await page.locator('#mode-single').click();assert.equal(await page.locator('#prompt').inputValue(),'保留专家草稿');
  await page.locator('#experience-easy').click();
  checks.push('centered header switches novice to Pavo, hides project/directory management, restores expert controls and preserves independent drafts');
  await page.screenshot({path:'test-results/novice-v123-desktop.png',fullPage:true});
  await page.evaluate(async()=>{const s=await import('./src/storage.js'),root=await navigator.storage.getDirectory(),folder=await root.getDirectoryHandle('experience-output',{create:true}),proto=Object.getPrototypeOf(folder);proto.queryPermission=async()=> 'granted';proto.requestPermission=async()=> 'granted';await s.put('handles','directory',folder);const p=await s.get('state','project');const draft=p.studios.find(x=>x.id===p.activeStudioId).draft;delete draft.pavoDefaultsVersion;draft.fields['pavo-aspect']='Auto';draft.fields['pavo-seconds']='4';await s.saveProject(p,folder);});
  await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  assert.equal(await page.locator('#mode-pavo').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#pavo-prompt').inputValue(),'保留 Pavo 草稿');assert.match(await page.locator('#pavo-settings-summary').textContent(),/16:9.*12s.*720p/);
  // Bypass only authentication transport waiting in this isolated test. The real UI/Runner/media checks execute.
  await page.evaluate(async()=>{const {Transport}=await import('./src/engine.js');window.__requests=[];Transport.prototype.api=async function(route,payload){if(payload){window.__requests.push(payload);return {video_id:'synthetic_'+window.__requests.length};}return {status:'completed',url:'https://synthetic.example.test/output.mp4'};};const {concatenate}=await import('./src/media.js');const input=await(await fetch('./tests/fixtures/synthetic.mp4')).blob();window.__wide=await concatenate([input],[1280,720]);Transport.prototype.media=async()=>window.__wide;});
  await page.locator('#experience-expert').click();await page.locator('#mode-single').click();await page.locator('#shot-id').fill('');await page.locator('#episode').fill('');await page.locator('#experience-easy').click();
  await page.locator('#mode-single').click();await page.locator('#prompt').fill('视频时长4秒，小熊走进森林。\n对白：小熊：你好。');await page.locator('#add-jobs').click();
  await page.locator('#jobs-grid .status.ready').waitFor({timeout:120000});
  const first=await page.evaluate(async()=>{const {get}=await import('./src/storage.js');return {job:(await get('state','project')).jobs[0],requests:window.__requests};});
  assert.equal(first.requests.length,1);assert.equal(first.requests[0].seconds,'4');assert.equal(first.requests[0].mode,'text');assert.equal(first.job.review,'pending');assert.equal(first.job.current.qa.fullDecode,'passed');assert.match(first.requests[0].prompt,/只说以下指定对白/);
  checks.push('novice one generate click runs checks, submit, query, download, decode and save; prompt 4 seconds overrides hidden 12; explicit dialogue retained; no content auto-approval');
  await page.locator('#new-from-queue').click();await page.locator('#mode-pavo').click();assert.equal(await page.locator('#pavo-submit').isDisabled(),false);assert.match(await page.locator('#submission-cooldown').textContent(),/冷却.*照常接收/);await expireCooldown();
  assert.equal(await page.locator('#single-editor').isVisible(),false);assert.equal(await page.locator('#batch-editor').isVisible(),false);assert.equal(await page.locator('#pavo-editor').isVisible(),true);assert.equal(await page.locator('.form-footer').isVisible(),false);
  await page.locator('#pavo-settings-toggle').click();await page.locator('[data-pavo-aspect="16:9"]').click();await page.locator('[data-pavo-seconds="12"]').click();assert.match(await page.locator('#pavo-settings-summary').textContent(),/16:9.*12s/);await page.locator('#pavo-settings-close').click();
  await page.locator('#pavo-prompt').fill('时长4秒，小熊转身。');await page.locator('#mode-single').click();assert.equal(await page.locator('#prompt').inputValue(),'');await page.locator('#mode-pavo').click();assert.match(await page.locator('#pavo-prompt').inputValue(),/小熊转身/);
  await page.screenshot({path:'test-results/pavo-v123-desktop.png',fullPage:true});
  const wideSize=await page.evaluate(async()=>{const {concatenate}=await import('./src/media.js'),{Transport}=await import('./src/engine.js');const long=await concatenate([window.__wide,window.__wide,window.__wide,window.__wide],[1280,720]);Transport.prototype.media=async()=>long;return long.size;});
  await page.locator('#pavo-submit').click();await page.locator('#jobs-grid .status.ready').nth(1).waitFor({timeout:120000});
  const second=await page.evaluate(async()=>{const {get}=await import('./src/storage.js');return {jobs:(await get('state','project')).jobs,requests:window.__requests};});assert.equal(second.requests.length,2);assert.equal(second.requests[1].seconds,'4');assert.equal(second.requests[1].aspect_ratio,'16:9');assert.equal(second.jobs[1].creationMode,'pavo');assert.equal(second.jobs[1].current.qa.technical,'passed');assert.ok(second.jobs[1].current.qa.duration>12);assert.equal(second.jobs[1].current.bytes,wideSize);
  const joined=await page.evaluate(async()=>{const {Runner}=await import('./src/engine.js'),{get,getFolder}=await import('./src/storage.js');const p=await get('state','project'),r=new Runner(()=>({project:p,folder:null}),()=>{},()=>{});const folder=await getFolder();r.context=()=>({project:p,folder});return await r.assemble('EP01');});assert.ok(joined.seconds>16);assert.equal(joined.fullDecode,'passed');
  checks.push('PavoAI has independent editor/draft, functional aspect/duration popup and one-click generation with prompt priority');
  await page.locator('#new-from-queue').click();await expireCooldown();await page.locator('#pavo-settings-toggle').click();for(const width of [1440,850,390]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.screenshot({path:'test-results/pavo-v123-mobile.png',fullPage:true});
  await page.locator('#mode-pavo').press('ArrowLeft');assert.equal(await page.locator('#mode-batch').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#pavo-editor').isVisible(),false);assert.equal(await page.locator('#single-editor').isVisible(),false);
  await page.setViewportSize({width:1440,height:1000});await page.locator('#mode-single').click();await page.screenshot({path:'test-results/easy-v123-desktop.png',fullPage:true});assert.deepEqual(errors,[]);
  checks.push('three tabs keyboard navigation, expert visibility and desktop/tablet/mobile layout without horizontal overflow');
  // Novice file selection validates and repairs without requiring a plan-confirmation click.
  const png=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=400;c.height=50;c.getContext('2d').fillRect(0,0,400,50);return [...new Uint8Array(await(await new Promise(r=>c.toBlob(r,'image/png'))).arrayBuffer())];});
  await page.locator('#mode-pavo').click();await page.locator('#asset-files').setInputFiles({name:'long-reference.png',mimeType:'image/png',buffer:Buffer.from(png)});
  await page.waitForFunction(()=>document.querySelector('#pavo-selected-assets .asset-chip')&&document.querySelector('#asset-operation-dialog').open===false);
  const imported=await page.evaluate(async()=>{const {get}=await import('./src/storage.js');return (await get('state','project')).assets;});assert.equal(imported.length,2);assert.equal(imported[0].name,imported[1].name);assert.equal(imported[1].derivedFrom,imported[0].id);assert.equal(imported[1].errors.length,0);assert.match(imported[1].path,/references\/optimized/);
  checks.push('Pavo upload validates and optimizes an invalid wide image automatically, preserves original filename and selects effective version');
  // A synthetic capability profile verifies dynamic labels without pretending a new live adapter exists.
  await page.evaluate(async()=>{const {MODEL_PROFILES}=await import('./src/models.js');MODEL_PROFILES.push({id:'test-profile',platformName:'测试平台',modelLabel:'测试模型',resolution:'1080P',modes:{text:{minSeconds:3,maxSeconds:20,step:1},reference:{minSeconds:3,maxSeconds:8,step:1}},references:{maxImages:2,maxAudio:1,minAudioSeconds:2,maxAudioSeconds:8}});const el=document.querySelector('#pavo-model');el.add(new Option('测试模型','test-profile'));el.value='test-profile';el.dispatchEvent(new Event('change',{bubbles:true}));});
  assert.equal(await page.locator('[data-current-platform]').textContent(),'测试平台');assert.match(await page.locator('.workspace-limit').textContent(),/3–8 秒/);assert.equal(await page.locator('.pavo-resolution').textContent(),'1080P');assert.equal(await page.locator('[data-pavo-seconds="12"]').count(),0);assert.match(await page.locator('.pavo-settings small').textContent(),/测试平台.*8 秒/);
  await page.screenshot({path:'test-results/sidebar-v123-dynamic.png',fullPage:true});await page.locator('#pavo-model').selectOption('agnes-video-2.5-flash');assert.equal(await page.locator('[data-current-platform]').textContent(),'AgnesAI');assert.equal(await page.locator('[data-pavo-seconds="12"]').count(),1);
  await page.screenshot({path:'test-results/sidebar-v123-desktop.png',fullPage:true});
  checks.push('selected provider name, resolution, mode-specific duration choices and limit label update from one capability registry');
  await page.locator('#mode-batch').click();await page.locator('#batch-input').fill(JSON.stringify({shots:[{id:'AUTO01',episode:'AUTO',seconds:12,video_prompt:'视频时长4秒，小熊点头。'},{id:'AUTO02',episode:'AUTO',seconds:12,video_prompt:'视频时长4秒，小熊挥手。'}]}));await page.locator('#add-jobs').click();await page.locator('#jobs-grid .status.ready').nth(3).waitFor({timeout:120000});
  const batch=await page.evaluate(async()=>{const {get}=await import('./src/storage.js');return {jobs:(await get('state','project')).jobs,requests:window.__requests};});assert.equal(batch.requests.length,4);assert.deepEqual(batch.jobs.slice(2).map(j=>j.seconds),[4,4]);assert.ok(batch.jobs.slice(2).every(j=>j.current.qa.technical==='passed'));
  checks.push('novice batch generates two structured video_prompt rows from one button, with per-shot prompt duration priority');
  await writeFile('test-results/experience-v123-results.json',JSON.stringify({version:'1.2.3',checks,errors,syntheticPosts:batch.requests.length,longReturnedSeconds:second.jobs[1].current.qa.duration,assembledSeconds:joined.seconds},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
}finally{await browser.close();}
