import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {sealLocalDefault} from '../src/local-default.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
const config=await sealLocalDefault('sk-synthetic-watchdog');await context.route('**/private/default-access.json',r=>r.fulfill({json:config}));await context.route('https://**',r=>{errors.push('Unexpected real upstream');return r.abort();});page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(process.env.XAI_TEST_URL||'http://127.0.0.1:4183/');await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
 const result=await page.evaluate(async()=>{
  const {Runner}=await import('./src/engine.js'),{QueueWatchdog}=await import('./src/queue-watchdog.js'),{makeProject,newJob}=await import('./src/core.js'),s=await import('./src/storage.js');
  let interval;const realInterval=window.setInterval;window.setInterval=(callback,ms)=>(interval=ms,0);const timing=new QueueWatchdog(()=>({}));try{await timing.install();}finally{window.setInterval=realInterval;window.removeEventListener('online',timing.wake);window.removeEventListener('pageshow',timing.wake);document.removeEventListener('visibilitychange',timing.wake);}
  const fixture=await(await fetch('./tests/fixtures/synthetic.mp4')).blob(),folder=await(await navigator.storage.getDirectory()).getDirectoryHandle('watchdog-fixture',{create:true}),base={id:'S03',episode:'EP01',seconds:4,aspect:'9:16',mode:'text',assetIds:[],prompt:'4秒，小熊挥手'};
  const p=makeProject(),j=newJob({...base,experience:'easy',creationMode:'pavo'});p.jobs=[j];p.events=[{kind:'input_approved',jobId:j.id}];const r=new Runner(()=>({project:p,folder}),()=>{},()=>{});r.transport.key='synthetic';let posts=0;r.transport.api=async(route,payload)=>payload?(posts++,{video_id:'receipt_'+posts}):{status:'completed',url:'https://synthetic.invalid/video.mp4'};r.transport.media=async()=>fixture;
  const w=new QueueWatchdog(()=>({project:p,runner:r,folder}));await Promise.all([w.tick(),w.tick(),w.tick()]);while(r.running||r.starting)await new Promise(resolve=>setTimeout(resolve,50));await w.tick();const migrated={auto:j.autoSubmit,state:j.state,posts,attempts:j.attempts.length};
  const next=newJob({...base,id:'S04',autoSubmit:true});p.jobs.push(next);await r.setPaused(true);await w.tick();const paused={posts,code:r.health.code,stored:p.queueControl.paused};await r.setPaused(false);await w.tick(); // restart cooldown prevents unnecessary duplicate wakeups
  w.nextRestartAt=0;await w.tick();while(r.running||r.starting)await new Promise(resolve=>setTimeout(resolve,50));const resumed={posts,state:next.state};
  const parallel=makeProject(),previous=newJob({...base,id:'P01',autoSubmit:true}),following=newJob({...base,id:'P02',autoSubmit:true});parallel.jobs=[previous,following];previous.state='download';previous.attempts=[{number:1,videoId:'previous',url:'https://synthetic.invalid/previous.mp4'}];
  const rr=new Runner(()=>({project:parallel,folder}),()=>{},()=>{});rr.transport.key='synthetic';let release;const gate=new Promise(resolve=>release=resolve),realAccept=rr.acceptFile.bind(rr);rr.acceptFile=async(job,...args)=>{if(job.id==='P01')await gate;return realAccept(job,...args);};let submittedWhileChecking=false;rr.transport.media=async()=>fixture;rr.transport.api=async(route,payload)=>{if(payload){submittedWhileChecking=previous.state==='checking';release();return {video_id:'following'};}return {status:'completed',url:'https://synthetic.invalid/following.mp4'};};await rr.start({automatic:true,onlyUids:[]});
  return {interval,migrated,paused,resumed,submittedWhileChecking,parallelStates:parallel.jobs.map(j=>j.state)};
 });
 assert.equal(result.interval,30000);assert.deepEqual(result.migrated,{auto:true,state:'ready',posts:1,attempts:1});assert.equal(result.paused.posts,1);assert.equal(result.paused.code,'paused');assert.equal(result.paused.stored,true);assert.equal(result.resumed.posts,2);assert.equal(result.resumed.state,'ready');assert.equal(result.submittedWhileChecking,true);assert.deepEqual(result.parallelStates,['ready','ready']);assert.deepEqual(errors,[]);
 // Real UI intake clears the prompt and material chips only once the queue is durable.
 await page.evaluate(async()=>{const s=await import('./src/storage.js'),{makeProject}=await import('./src/core.js'),out=await(await navigator.storage.getDirectory()).getDirectoryHandle('watchdog-ui',{create:true});await s.put('handles','directory',out);await s.saveProject(makeProject(),out);});await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
 await page.evaluate(async()=>{const {Transport}=await import('./src/engine.js');Transport.prototype.api=async(route,payload)=>payload?{video_id:'ui-intake'}:{status:'completed',url:'https://synthetic.invalid/ui.mp4'};Transport.prototype.media=async()=>await(await fetch('./tests/fixtures/synthetic.mp4')).blob();});
 const png=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=800;c.height=500;c.getContext('2d').fillRect(0,0,800,500);return [...new Uint8Array(await(await new Promise(r=>c.toBlob(r,'image/png'))).arrayBuffer())];});await page.locator('#asset-files').setInputFiles({name:'watchdog-reference.png',mimeType:'image/png',buffer:Buffer.from(png)});await page.waitForFunction(()=>document.querySelector('#pavo-selected-assets .asset-chip')&&!document.querySelector('#asset-operation-dialog').open);
 await page.locator('#pavo-prompt').fill('4秒，小熊挥手，测试入队清空。');await page.locator('#pavo-submit').click();await page.waitForFunction(()=>document.querySelectorAll('.job-card').length===1&&document.querySelector('#pavo-prompt').value==='');assert.equal(await page.locator('#pavo-selected-assets .asset-chip').count(),0);await page.locator('#new-from-queue').click();assert.match(await page.locator('#pavo-settings-summary').textContent(),/16:9.*12s.*720p/);
 const stored=await page.evaluate(async()=>await(await import('./src/storage.js')).get('state','project'));assert.match(stored.jobs[0].prompt,/测试入队清空/);assert.equal(stored.jobs[0].assetIds.length,1);assert.equal(stored.studios[0].draft.fields['pavo-prompt'],'');
 await page.screenshot({path:'test-results/watchdog-v123-desktop.png',fullPage:true});
 await page.locator('#pavo-prompt').fill('视频时长30秒，超出当前API请求范围。');await page.locator('#pavo-submit').click();await page.waitForTimeout(300);assert.match(await page.locator('#pavo-prompt').inputValue(),/30秒/);assert.equal(await page.locator('.job-card').count(),1);
 await page.locator('#pavo-prompt').fill('视频时长4秒，保存失败时保留这一段。');await page.waitForTimeout(700);
 await page.evaluate(()=>{window.__realFileHandle=FileSystemDirectoryHandle.prototype.getFileHandle;FileSystemDirectoryHandle.prototype.getFileHandle=function(name,...args){if(name==='project.json')throw new DOMException('Synthetic disk full','QuotaExceededError');return __realFileHandle.call(this,name,...args);};});
 await page.locator('#pavo-submit').click();await page.waitForTimeout(400);assert.match(await page.locator('#pavo-prompt').inputValue(),/保存失败/);assert.equal(await page.locator('.job-card').count(),1);const afterFailure=await page.evaluate(async()=>{FileSystemDirectoryHandle.prototype.getFileHandle=__realFileHandle;return await(await import('./src/storage.js')).get('state','project');});assert.equal(afterFailure.jobs.length,1);assert.deepEqual(errors,[]);
 await writeFile('test-results/watchdog-v123-results.json',JSON.stringify({checks:['legacy novice approved intake self-resumes once; pause intent survives and resume works','saved previous original releases next submission while full technical check continues','durable UI intake clears prompt/materials and preserves queued snapshot; invalid input remains'],result,errors},null,2));console.log(JSON.stringify({passed:3,result,errors},null,2));
}finally{await browser.close();}
